version: '3.7'
services:
  redis:
    image: redis:latest
    command: redis-server
    restart: on-failure
    ports:
      - "6378:6379"

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=2131
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
        - "5433:5432"
  bot:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python -m mainbot & celery -A notifications_sending worker -B --uid myuser "
    restart: always
    depends_on:
      - db
      - redis

volumes:
  pgdata:
